GET http://localhost:3000/api/colaboradores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWNlN2M1OTQtNGVmNy00NmExLTg4ZmItMTY1OTEwODE1MTAzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MjkzNzIwLCJleHAiOjE3MTkyOTQ5MjB9.BigApxOZ-iOjN6NRIZDNxBNHV3PZ-7ccT7mcDLNfcf0


###

GET http://servidor/langroup/api/colaboradores?rol=Administrador
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE4NzU5NTc1LCJleHAiOjE3MTg3NjA3NzV9.RodUpBV8WcWCcIfwUQw4w14vKiloZwWey0nRCxRM97E

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "correo": "zS21013868@estudiantes.uv.mx",
    "contrasenia": "Langroup123-"
}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "correo": "prueba12@uv.mx",
    "contrasenia": "P4ssw0rd-"
}


###

GET http://localhost:3000/api/grupos?colaboradorid=d322880b-279d-49c4-ade1-c18b7e6b6419&rol=Administrador
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MTAzNTAzLCJleHAiOjE3MTkxMDQ3MDN9.zPPSHThwlkDOP8Z7CzsFb0B6XtOmG7fyq7SL17bER2w


###

POST http://localhost:3000/api/grupos/colaboradores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MTE0MzYwLCJleHAiOjE3MTkxMTU1NjB9.o3Md48Wmo0bkmapqx5Jp7ngdgp0dGA3SLB1hbBiGRl0
Content-Type: application/json

{
    "colaboradorid": "3567481f-2ab9-403c-8c3e-e9fd73109760",
    "grupoid": "85b31413-fa22-46c3-b88e-6fc422b81230",
    "rol": "Administrador"
}


###

POST http://localhost:3000/api/idiomas/colaboradores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MDkyMTU2LCJleHAiOjE3MTkwOTMzNTZ9.WJBfDVUrsp1vl92rYd_t1kvDFm3fo7L_XY2L8gTOrFA
Content-Type: application/json

{
    "colaboradorid": "d4c0f323-7a48-4e6b-a3ec-00d559c7c421",
    "idiomaid": "32969888-daec-4016-9d1e-0e7a40502b33"
}


###
GET https://cf49-200-68-170-82.ngrok-free.app/langroup/api/colaboradores


###

POST https://c658-200-68-170-82.ngrok-free.app/langroup/api/auth
Content-Type: application/json

{
    "correo": "zS21013868@estudiantes.uv.mx",
    "contrasenia": "Langroup123-"
}


###

GET http://localhost:3000/api/grupos?colaboradorid=d4c0f323-7a48-4e6b-a3ec-00d559c7c421
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MTExMDEzLCJleHAiOjE3MTkxMTIyMTN9.gj-UHiu9FSiHSmFAjx3iQJ_2WRCwcnX2FzQs2XSG9_Y


###

GET http://localhost:3000/api/grupos/85b31413-fa22-46c3-b88e-6fc422b81230
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MTExMDEzLCJleHAiOjE3MTkxMTIyMTN9.gj-UHiu9FSiHSmFAjx3iQJ_2WRCwcnX2FzQs2XSG9_Y


###

GET http://localhost:3000/api/grupos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MTEyMTc2LCJleHAiOjE3MTkxMTMzNzZ9.3BB2IjewDCuOUrnzdueEsx0Aeuws1mBeyr9n93jvGus


###

GET http://localhost:3000/api/grupos?rol=Participante
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MTExMDEzLCJleHAiOjE3MTkxMTIyMTN9.gj-UHiu9FSiHSmFAjx3iQJ_2WRCwcnX2FzQs2XSG9_Y

###

GET http://localhost:3000/api/idiomas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MTEyMTc2LCJleHAiOjE3MTkxMTMzNzZ9.3BB2IjewDCuOUrnzdueEsx0Aeuws1mBeyr9n93jvGus


###

GET http://localhost:3000/api/idiomas?colaboradorid=d4c0f323-7a48-4e6b-a3ec-00d559c7c421
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MTEyMTc2LCJleHAiOjE3MTkxMTMzNzZ9.3BB2IjewDCuOUrnzdueEsx0Aeuws1mBeyr9n93jvGus


###

POST http://localhost:3000/api/grupos/colaboradores
Content-Type: application/json

{
    "colaboradorid": "1598cff6-c78a-409f-b36e-fa584bd58dd7",
  "grupoid": "3568ed2b-c02b-4877-bc78-66b09fec070f",
  "rol": "Participante"
}


###
POST http://localhost:3000/api/publicaciones
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MzA5Mzk1LCJleHAiOjE3MTkzMTA1OTV9.Z0A8C3he5k6GlmmHyVM68KYI3suo7c0zfrd0O1-Jg44
Content-Type: application/json

{
    "titulo": "Publicación de ejemplo",
    "descripcion": "Esta es una prueba",
    "colaboradorid": "3567481f-2ab9-403c-8c3e-e9fd73109760",
    "grupoid": "85b31413-fa22-46c3-b88e-6fc422b81230"
}


###

POST http://localhost:3000/api/interacciones
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZDMyMjg4MGItMjc5ZC00OWM0LWFkZTEtYzE4YjdlNmI2NDE5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoicHJ1ZWJhVXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFwcmVuZGl6IiwiaXNzIjoiU2Vydmlkb3JMYW5Hcm91cEpXVCIsImF1ZCI6IkNsaWVudGVzTGFuR3JvdXBKV1QiLCJpYXQiOjE3MTkyODMxNzYsImV4cCI6MTcxOTI4NDM3Nn0.C2aU3AKBDcoYMUde-OLFnw4waEcZfXP3KXcsYs1J-lo
Content-Type: application/json

{
    "valoracion": 4,
    "comentario": "Es una buena publicación",
    "colaboradorid": "d322880b-279d-49c4-ade1-c18b7e6b6419",
    "publicacionid": "5e17c944-95e2-4025-94be-935c6ae9bae5"
}


###

GET http://localhost:3000/api/interacciones/5e17c944-95e2-4025-94be-935c6ae9bae5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MjkyMzI5LCJleHAiOjE3MTkyOTM1Mjl9.ERgLOMRg0fb9nR5kfdiVvJgtQ7_3DN3C6V7D_jKzJOY


####

GET http://localhost:3000/api/publicaciones
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE5MjkyMzI5LCJleHAiOjE3MTkyOTM1Mjl9.ERgLOMRg0fb9nR5kfdiVvJgtQ7_3DN3C6V7D_jKzJOY
