GET http://localhost:3000/api/colaboradores/85dccdbb-6ea8-4c03-ab72-b705efe55a0b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE3MzgwOTIxLCJleHAiOjE3MTczODIxMjF9.OgzMF3aqJcZ58qCcC2AVpKQkF9ogffnUoOyJOTGDO_k

###

GET http://localhost:3000/api/colaboradores?rol=Administrador
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYjA3ZWI5M2YtZWEzYi00YzEwLTk4NTEtZWU4YTU4OWE3NjQxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE3NDIxMDQxLCJleHAiOjE3MTc0MjIyNDF9.qkZhhuH3Vqnmk-PusJDGul9Trqv6oY-m2ER9jcjl7wU

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "correo": "zS21013868@estudiantes.uv.mx",
    "contrasenia": "langroup"
}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "correo": "pruebaUser3@uv.mx",
    "contrasenia": "p4ssw0rd"
}


###