GET http://localhost:3000/api/colaboradores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE4OTk0NTgyLCJleHAiOjE3MTg5OTU3ODJ9.yPqfmb-t4mxPI6dZyvF8FDfwJF62WzNCQrttRguJ5-I

###

GET http://servidor/langroup/api/colaboradores?rol=Administrador
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE4NzU5NTc1LCJleHAiOjE3MTg3NjA3NzV9.RodUpBV8WcWCcIfwUQw4w14vKiloZwWey0nRCxRM97E

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "correo": "zS21013868@estudiantes.uv.mx",
    "contrasenia": "Langroup123-"
}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "correo": "prueba10@uv.mx",
    "contrasenia": "P4ssw0rd-"
}


###

GET http://localhost:3000/api/grupos/3567481f-2ab9-403c-8c3e-e9fd73109760/Administrador
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzU2NzQ4MWYtMmFiOS00MDNjLThjM2UtZTlmZDczMTA5NzYwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoibGFuZ3JvdXB1c3VhcmlvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yTGFuR3JvdXBKV1QiLCJhdWQiOiJDbGllbnRlc0xhbkdyb3VwSldUIiwiaWF0IjoxNzE4OTk0NTgyLCJleHAiOjE3MTg5OTU3ODJ9.yPqfmb-t4mxPI6dZyvF8FDfwJF62WzNCQrttRguJ5-I


###

POST http://localhost:3000/api/grupos/colaboradores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZDRjMGYzMjMtN2E0OC00ZTZiLWEzZWMtMDBkNTU5YzdjNDIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoicHJ1ZWJhVXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFwcmVuZGl6IiwiaXNzIjoiU2Vydmlkb3JMYW5Hcm91cEpXVCIsImF1ZCI6IkNsaWVudGVzTGFuR3JvdXBKV1QiLCJpYXQiOjE3MTg5OTY5NjQsImV4cCI6MTcxODk5ODE2NH0.ip5LVMmAclDOrSO2_G-FfRs26rYh5Yg9SFOHUXSXRYw
Content-Type: application/json

{
    "colaboradorid": "d4c0f323-7a48-4e6b-a3ec-00d559c7c421",
    "grupoid": "85b31413-fa22-46c3-b88e-6fc422b81230",
    "rol": "Participante"
}


###

POST http://localhost:3000/api/idiomas/colaboradores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZDRjMGYzMjMtN2E0OC00ZTZiLWEzZWMtMDBkNTU5YzdjNDIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoicHJ1ZWJhVXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFwcmVuZGl6IiwiaXNzIjoiU2Vydmlkb3JMYW5Hcm91cEpXVCIsImF1ZCI6IkNsaWVudGVzTGFuR3JvdXBKV1QiLCJpYXQiOjE3MTg5OTY5NjQsImV4cCI6MTcxODk5ODE2NH0.ip5LVMmAclDOrSO2_G-FfRs26rYh5Yg9SFOHUXSXRYw
Content-Type: application/json

{
    "colaboradorid": "d4c0f323-7a48-4e6b-a3ec-00d559c7c421",
    "idiomaid": "32969888-daec-4016-9d1e-0e7a40502b33"
}


###