GET http://localhost:3000/api/interacciones/p1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoielMyMTAxMzg2OEBlc3R1ZGlhbnRlcy51di5teCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6Imxhbmdyb3VwdXN1YXJpbyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpc3MiOiJTZXJ2aWRvckxhbkdyb3VwSldUIiwiYXVkIjoiQ2xpZW50ZXNMYW5Hcm91cEpXVCIsImlhdCI6MTcxNzE5ODgxOCwiZXhwIjoxNzE3MjAwMDE4fQ.xT_KXloufFCvWy29cZuSQpBuVCihaRcfSoLL0tFSp4k

###

POST http://localhost:3000/api/interacciones
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoielMyMTAxMzg2OEBlc3R1ZGlhbnRlcy51di5teCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6Imxhbmdyb3VwdXN1YXJpbyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpc3MiOiJTZXJ2aWRvckxhbkdyb3VwSldUIiwiYXVkIjoiQ2xpZW50ZXNMYW5Hcm91cEpXVCIsImlhdCI6MTcxNjgzMDgyMSwiZXhwIjoxNzE2ODMyMDIxfQ.9lo80w7nSEpVr9gRgSTqaUsD8HUlp2axoe_wmFyhTp8

{
    "valoracion": "5",
    "comentario": "muy buena explicación",
    "fecha": "2024-05-26 18:55:31",
    "colaboradorid": "d7a2ead5-8f1e-4da0-9ba5-b2203dc6c5a6",
    "publicacionid": "p1"
}

###

PUT http://localhost:3000/api/interacciones/023b9b65-1b7c-47a8-8c79-4e358fc49b55
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoielMyMTAxMzg2OEBlc3R1ZGlhbnRlcy51di5teCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6Imxhbmdyb3VwdXN1YXJpbyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpc3MiOiJTZXJ2aWRvckxhbkdyb3VwSldUIiwiYXVkIjoiQ2xpZW50ZXNMYW5Hcm91cEpXVCIsImlhdCI6MTcxNzE5ODgxOCwiZXhwIjoxNzE3MjAwMDE4fQ.xT_KXloufFCvWy29cZuSQpBuVCihaRcfSoLL0tFSp4k

{
    "valoracion": "4",
    "comentario": "no es tan buena realmente"
}

###

DELETE http://localhost:3000/api/interacciones/023b9b65-1b7c-47a8-8c79-4e358fc49b55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoielMyMTAxMzg2OEBlc3R1ZGlhbnRlcy51di5teCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6Imxhbmdyb3VwdXN1YXJpbyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpc3MiOiJTZXJ2aWRvckxhbkdyb3VwSldUIiwiYXVkIjoiQ2xpZW50ZXNMYW5Hcm91cEpXVCIsImlhdCI6MTcxNjgzMDgyMSwiZXhwIjoxNzE2ODMyMDIxfQ.9lo80w7nSEpVr9gRgSTqaUsD8HUlp2axoe_wmFyhTp8

###